[package]
name = "pushkind-sms"
version = "0.1.0"
edition = "2024"

[dependencies]
aws-config = "1.8.10"
aws-sdk-sns = "1.90.0"
tokio = { version = "1.48.0", features = ["full"] }
dotenvy = "0.15.7"
env_logger = "0.11.8"
log = "0.4.27"
